- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'f982163f-efcd-4e90-9346-80af0b921c3f'
    location: 'Brazil Southeast'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/javieretchepare/demodevops2.git'
    deploymentMode: 'Incremental'
    deploymentName: 'demo2'