# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'f982163f-efcd-4e90-9346-80af0b921c3f'
    location: 'Brazil South'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/javieretchepare/AzDevevOpsPipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
